**NPTEL-Week-03**


**Name**: Yashraj Patil

**Roll no**: 23102A0071

**Department and Division**: CMPN-A

**Lab mentor**: Prof. Prakash Parmar

In [1]:
# Addition with data vectors
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [2]:
# Power operator
2^3
2**3

[1] 8

[1] 8

In [3]:

2^0.5
2**0.5
2^-0.5

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [4]:
# Power operation on a vector
c(2,3,5,7)^2

[1]  4  9 25 49

In [6]:
# Power operation with vectors
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [8]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [9]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [10]:
# Integer division
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

In [11]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [12]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [13]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [14]:
# Modulo division
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

In [15]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [16]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [17]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [18]:
# Maximum
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

In [19]:
# Minimum
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

In [20]:
# Arithmetic mean
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

In [21]:
# Absolute value
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

In [22]:
# Square root
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

In [23]:
# Sum
sum(c(2,3,5,7))

[1] 17

In [24]:
# Product
prod(c(2,3,5,7))

[1] 210

In [25]:
# Round
round(1.23)
round(1.83)

[1] 1

[1] 2

In [26]:
# Natural logarithm
log(10)
log(exp(1))
log(c(10,100,1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

In [27]:
# Logarithm base 10
log10(10)
log10(100)
log10(c(10,100,1000))

[1] 1

[1] 2

[1] 1 2 3

In [28]:
# Assignments
x1 = c(1,2,3,4)
x1

x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [29]:
# Calculations with vectors and functions
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [30]:
abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)))

[1] 19 18 17 16

In [31]:
# Create a 4 x 2 matrix
x = matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8)
)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [32]:
# Access a specific matrix element
x[3,2]

[1] 7

In [33]:
# Enter data column-wise
x = matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8)
)

In [34]:
# Equivalent explicit form
x = matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8),
  byrow=FALSE
)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [36]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [37]:
# Enter data row-wise
y = matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8),
  byrow=TRUE
)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [38]:
# Matrix properties
dim(x)

nrow(x)

ncol(x)

[1] 4 2

[1] 4

[1] 2

In [39]:
# Matrix mode
mode(x)

[1] "numeric"

In [40]:
# Matrix attributes
attributes(x)

$dim
[1] 4 2

In [41]:
# R help for matrix
help("matrix")

In [42]:
# Matrix functions
matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
       dimnames = NULL)
as.matrix(x)
is.matrix(x)

     [,1]
[1,] NA

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] TRUE

In [43]:
# Examples
is.matrix(as.matrix(1:10))

[1] TRUE

In [44]:
data(warpbreaks)

In [45]:
!is.matrix(warpbreaks)
warpbreaks[1:10,]
as.matrix(warpbreaks[1:10,])

[1] TRUE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M