**NPTEL-Week-03: Calculations with Data Vectors :
Addition, Subtraction, Multiplication & Division**


**Name**: Yashraj Patil

**Roll no**: 23102A0071

**Department and Division**: CMPN-A

**Lab mentor**: Prof. Prakash Parmar

### Addition with data vectors

In [1]:
 c(2,3,5,7) + c (-2, -3, -5 ,8 )

[1]  0  0  0 15

###Power operator with scalar and vector

In [2]:
2^3

[1] 8

In [4]:
2**3

[1] 8

In [5]:
2^0.5

[1] 1.414214

In [6]:
2**0.5

[1] 1.414214

In [7]:
2^-0.5

[1] 0.7071068

In [8]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [9]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [11]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [12]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

## Integer division with scalar and data vector

In [13]:
2 %% 2

[1] 0

In [14]:
5 %% 2

[1] 1

In [15]:
7 %% 3

[1] 1

In [17]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [19]:
c (2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [21]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

### Modulo Division (x mod y) with scalars

In [22]:
2 %% 2

[1] 0

In [23]:
3 %% 2

[1] 1

In [24]:
7 %% 3

[1] 1

In [25]:
7 %% 4

[1] 3

In [26]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [28]:
c (2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [29]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

###Maximum Operator: max

In [30]:
max (1.2, 3.4, -7.8)

[1] 3.4

In [31]:
max (c(1.2,3.4, -7.8))

[1] 3.4

### Minimum Operator: *min*

In [32]:
min (1.2, 3.4, -7.8)

[1] -7.8

In [33]:
min (c(1.2,3.4, -7.8))

[1] -7.8

## Arithmetic mean Operator: mean

In [34]:
mean(2,3,4)

[1] 2

In [35]:
 mean(c(2, 3, 4))

[1] 3

### Operator: abs for finding the absolute values

In [36]:
abs(-4)

[1] 4

In [37]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

### Operator: sqrt for finding the square root of values

In [38]:
sqrt(4)

[1] 2

In [39]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

### Operator: sum for finding the sum of values

In [40]:
sum(c(2,3,5,7))

[1] 17

###Operator: prod for finding the product of values

In [41]:
prod(c(2,3,5,7))

[1] 210

### Operator: round for finding the round off

In [42]:
round(1.23)

[1] 1

In [43]:
round(1.83)

[1] 2

##Operator: log for finding the natural log (ln) of values

In [44]:
log(10)

[1] 2.302585

In [45]:
log(exp(1))

[1] 1

In [46]:
log(c(10,100,1000))

[1] 2.302585 4.605170 6.907755

###Operator: log10 for finding the log (with base 10) of values

In [47]:
log10(10)

[1] 1

In [48]:
log10(100)

[1] 2

In [49]:
log10(c(10,100,1000))

[1] 1 2 3

### Assignments
An assignment can also be used to save values in variables:

In [50]:
x1 = c(1,2,3,4)

In [51]:
x1

[1] 1 2 3 4

In [52]:
x2 = x1^2
x2

[1]  1  4  9 16

### Assignments
Calculations with scalar, data vector and built in functions also work.

In [53]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(1,2)

[1] 21 22 23 24

In [55]:
abs(c(1,2,3,4)) - sum (c(1,2,3,4))* prod(c(1,2))

[1] -19 -18 -17 -16

###Matrix
Matrices are important objects in any calculation.

A matrix is a rectangular array with p rows and n columns.

In [56]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [57]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

###Matrix parameters

In [58]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [59]:
x[3,2]

[1] 7

### Entering data column wise in a matrix

In [60]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8))

In [61]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = FALSE)

## Entering data row wise in a matrix

In [62]:
y = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

In [63]:
 x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )

##Properties of a Matrix

In [65]:
dim(x)

[1] 4 2

In [66]:
nrow(x)

[1] 4

In [67]:
ncol(x)

[1] 2

In [68]:
mode(x)

[1] "numeric"

In [69]:
attributes(x)

$dim
[1] 4 2

In [70]:
help("matrix")