**NPTEL-Week-09: Strings – Display and Formatting**


**Name**: Yashraj Patil

**Roll no**: 23102A0071

**Department and Division**: CMPN-A

**Lab mentor**: Prof. Prakash Parmar

### Lecture 36: Print and Format with Concatenation

### `print()` limitation trying to print multiple items gives an error

In [59]:
print("The zero occurs at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occurs at", 2 * pi, "radians."): invalid 'quote' argument

### The only way with `print` is to print items one at a time

In [11]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

### `cat()` combine multiple items into continuous output

In [12]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

### `cat()` with `date()`

In [13]:
d = date()
cat("Today\u2019s date is:", d, "\n")

Today’s date is: Wed Sep 23 15:50:01 2026

### `cat()` with `sep` argument on a vector

In [14]:
x = 1:10
x
cat(x, sep =" ++ ")
cat("\n")   # This is used to change line
cat(x, sep =" / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

### `cat()` combining text and computed values

In [15]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

### `cat()` with `format()`

In [16]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

### `cat()` can also print simple vectors

In [17]:
evenno = c(2,4,6,8,10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

### `cat()` with `fill` and `labels`

In [18]:
x = 1:10
x
cat(x, fill = 2, labels = paste("(", letters[1:10], ")"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ) 1
( b ) 2
( c ) 3
( d ) 4
( e ) 5
( f ) 6
( g ) 7
( h ) 8
( i ) 9
( j ) 10

## Lecture 37: Paste Function

### `paste()` converts arguments to character strings (via `as.character`)

In [19]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [20]:
as.character(1:12)   #Alternative to paste

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

### `paste()` with default separator (space)

In [21]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

### `paste()` with custom `sep`

In [22]:
paste("Everybody", "loves", "R Programming.", sep="*")

[1] "Everybody*loves*R Programming."

In [23]:
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody===loves===R Programming."

### `paste()` with vectors of strings generates all combinations

In [24]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr. Jha")
names

[1] "Prof. Singh" "Mr.  Venkat" "Dr. Jha"

In [25]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr.  Venkat is a good person."
[3] "Dr. Jha is a good person."

### `paste()` with `collapse` join all combinations into one string

In [26]:
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh is a good person., and Mr.  Venkat is a good person., and Dr. Jha is a good person."

### Role of blank space inside double quotes with `sep`

In [27]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [28]:
paste(1, " is first   ", 2, " is second   ", 3, " is third   ", sep = "#")

[1] "1# is first   #2# is second   #3# is third   "

### `paste()` producing a vector of strings; indexing elements

In [29]:
x = paste("Ex", 1:5, sep="_")
x
x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

### `paste()` with `collapse` producing a single string instead of a vector

In [30]:
x = paste("Ex", 1:5, sep="_", collapse="")
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

### Difference between `paste` with and without `collapse`

In [31]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [32]:
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

### `paste0()` vs `paste()` for a single vector

In [33]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [34]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

### `paste0()` and `paste()` with more than one vector (vectorized concatenation)

In [35]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [36]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

## Lecture 38: String Splitting

### `strsplit()` basics

In [37]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [38]:
strsplit(x, split="!")

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

### `strsplit()` with a multi-character split string

In [39]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

### `strsplit()` result stored in a variable and accessing components

In [40]:
y = strsplit(x, split = "!&")
y

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [41]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [42]:
y[[1]][2]

[1] "available! &inthe online-help"

In [43]:
y[[1]][3]

[1] NA

### Example: Convert split dates to a matrix

In [44]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
dates

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

In [45]:
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [46]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [47]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

### `strsplit()` splitting into individual characters

In [48]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

## Lecture 39: Manipulations with Strings and Alphabets

### `nchar()` — count characters

In [49]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nchar(x)  #Count the Number of Characters
nchar(y)  #Count the Number of Characters

[1] 19

[1] 26

### `nzchar()` — check for non-empty strings

In [50]:
nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

### `nzchar()` on a character vector

In [51]:
x = c("Apple", "Banana", "Cake")
x
nzchar(x)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

In [52]:
y = c("Apple", "", "Cake")
y
nzchar(y)

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

### `nchar()` on character and numeric vectors

In [53]:
x = c("Apple", "Banana", "Cake")
nchar(x)

[1] 5 6 4

In [54]:
y = c(2, 4, 6)
nchar(y)

[1] 1 1 1

In [55]:
z = c(11, 222, 3333)
nchar(z)

[1] 2 3 4

In [56]:
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 3 4 5

### `tolower()` and `toupper()`

In [57]:
x = "R course will start from 24.07.2022"
x
toupper(x)

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

In [58]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"
z
tolower(z)

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"