**NPTEL WEEK-04**

**Name**: Yashraj Patil

**Roll no**: 23102A0071

**Department and Division**: CMPN-A

**Lab mentor**: Prof. Prakash Parmar

1. Create a matrix

In [1]:
x = matrix(nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

2. Rename row names

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

3. Rename column names

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

4. Assign the same number to all elements

In [4]:
x = matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

5. Identity matrix

In [5]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

6. Diagonal matrix with 5

In [6]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

7. Transpose of a matrix

In [7]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

8. Row and column sums

In [9]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x
rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

9. Row and column means

In [10]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x
rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

Lecture 14 — Matrix Access & Mathematical Operations

10. Create matrix

In [11]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

11. Access a row

In [12]:
x[3,]

[1] 7 8 9

12. Access a column

In [14]:
x[,2]

[1]  2  5  8 11 14

13. Access a submatrix

In [15]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

14. Select specific rows and columns

In [16]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

15. Add scalar to matrix

In [17]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x+5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

16. Subtract scalar

In [18]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x - 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

17. Multiply by scalar

In [19]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
5*x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

18. Divide by scalar

In [20]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x/2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

19. Addition and subtraction of matrices

In [21]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x
y
x + y
x - y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

Lecture 15 — Mathematical & Other Matrix Operations

20. Scalar multiplication

In [23]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
4*x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

21. Matrix expressions

In [24]:
x + 4*x
4*x - x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

22. Matrix multiplication

In [25]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x
y
x%*%y
y%*%x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

23. Transpose and matrix multiplication

In [26]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
t(x)
t(x) %*% x
x %*% t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

24. Cross product

In [27]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
t(x)
crossprod(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

25. Row-wise concatenation

In [29]:

x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y
rbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

26. Column-wise concatenation

In [30]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y
cbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

27. Inverse of a matrix

In [32]:
y = matrix(nrow = 2, ncol = 2, byrow = T,
           data = c(84,100,100,120))
y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

28. Eigenvalues and eigenvectors

In [33]:
y = matrix(nrow = 2, ncol = 2, byrow = T,
           data = c(84,100,100,120))
y
eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

Lecture 16 — Logical Operators

29. OR — ||

In [34]:
x=8
(x < 10) || (x < 2)
x=18
(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

30. | versus ||

In [35]:
x = c(8,18)
(x < 10) || (x < 2)
(x < 10) | (x < 2)

ERROR: Error in (x < 10) || (x < 2): 'length = 2' in coercion to 'logical(1)'

31. AND — &&

In [37]:
x = 5
(x < 10) && (x > 2)
x = 15
(x < 10) && (x > 2)

[1] TRUE

[1] FALSE

32. & versus &&

In [39]:
x = c(8,18)
(x < 10) && (x > 2)

ERROR: Error in (x < 10) && (x > 2): 'length = 2' in coercion to 'logical(1)'

In [40]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

33. Find values satisfying two conditions

In [41]:
x = 1:6
(x > 2) & (x < 5)
x[(x > 2) & (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

34. OR condition

In [42]:
x = 1:6
(x > 2) | (x < 5)
x[(x > 2) | (x < 5)]

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

35. && checks only the first element

In [45]:
x = 1:6
(x > 2) && (x < 5)

ERROR: Error in (x > 2) && (x < 5): 'length = 6' in coercion to 'logical(1)'

In [46]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

Lecture 17 — Relational & Logical Operators
36. Logical AND, OR, NOT

In [47]:
x = TRUE
y = FALSE
x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

37. Check whether a result is logical

In [48]:
x = 5

Logical1 = (x > 2)
Logical1
is.logical(Logical1)

Logical2 = (x < 10)
Logical2
is.logical(Logical2)

Logical3 = (x != 5)
Logical3
is.logical(Logical3)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

38. More logical expressions

In [49]:
x = 5

Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)

Logical5 = (3*x <20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

39. Basic relational comparisons

In [50]:
8 > 7
7 < 5
7 > 7
7 >= 7
8 < 8
8 <= 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

40. Equality and inequality

In [52]:
8 != 9
9 != 9
7 == 7
7 == 8

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

In [53]:
x = TRUE
!x

[1] FALSE

41. Compare two vectors

In [55]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

42. isTRUE() and isFALSE()

In [57]:
isTRUE(8 < 6)
isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE